version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/AppleFitnessWorkoutMapper"
  schedule:
    interval: daily
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
